# basic Go workflow

name: GO CI

on:
  pull_request:
    branches:
    - master
    - release
    paths:
    - 'apis/trips/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./apis/trips

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Build
        run: go build -v
      - name: Test
        run: go test ./tests
        
        
